PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE personagens (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
	nome VARCHAR (50),
	xp INTEGER,
	vida INTEGER,
	forca INTEGER,
	inteligencia INTEGER,
	rapidez INTEGER
);
COMMIT;
